# application config
server:
  port: ${SERVER_PORT:8081}

  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/auth/command/api}

# spring config
spring:
  application:
    name: ${APPLICATION_NAME:7fb1eb656c67a714e53976eda9ffb32a2022c03129f87425419cbe83521e643a}

  # hibernate config
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}
    hibernate:
      naming:
        physical-strategy: ${HIBERNATE_NAMING:org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl}

  # rabbitmq config
  rabbitmq:
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    ignoreDeclarationException: ${RABBITMQ_IGNORE_DECLARATION_EXCEPTION:true}
    concurrentConsumers: ${RABBITMQ_CONCURRENT_CONSUMERS:3}
    maxConcurrentConsumers: ${RABBITMQ_MAX_CONCURRENT_CONSUMERS:10}
    receiveTimeout: ${RABBITMQ_RECEIVE_TIMEOUT:100000}

  # datasource config
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/AuthCommandService}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:12345678}

# keycloak
keycloak:
  realm: ${KEYCLOAK_REALM:Habolabu}
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:https://keycloak-habolabu-nguyentrungkien01.cloud.okteto.net/auth/}
  ssl-required: ${KEYCLOAK_SSL_REQUIRED:none}
  resource: ${KEYCLOAK_RESOURCE:Habolabu}
  bearer-only: ${KEYCLOAK_BEARER_ONLY:true}
  cors: ${KEYCLOAK_CORS:true}
  config:
    username: ${KEYCLOAK_USERNAME:admin}
    password: ${KEYCLOAK_PASSWORD:12345678}
    clientId: ${KEYCLOAK_CLIENT_ID:habolabu-back-end-service}
    clientSecret: ${KEYCLOAK_CLIENT_SECRET:Lo4PmPoTWYMT6BmzF1f2ir6dlkJ9RiTq}
